# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  lint-app:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v
            npm -v
            npm cache clean --force

            echo "BUILD ALL IMAGES"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed longtm4/udagram-api-feed:v1

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user longtm4/udagram-api-user:v1
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend longtm4/udagram-frontend:v6

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy longtm4/udagram-reverseproxy:v1
            echo "SUCCESS create images"

            echo "LOGIN TO DOCKER HUB"
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            echo "PUSH ALL IMAGES TO DOCKER HUB"
            docker push longtm4/udagram-api-feed:v1
            docker push longtm4/udagram-api-user:v1
            docker push longtm4/udagram-frontend:v6
            docker push longtm4/udagram-reverseproxy:v1

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
